### ISSUE TITLE
Next.js + Happypack module

### ISSUE THREAD

**Issue by ygpark80** [zigbang/next.js#1]
https://github.com/zigbang/next.js/commit/46f6c79d7d2b1161d61838a8af17f4d0cedc32b9 의 변동사항을 보니 happypack을 이용한 것으로 보입니다. (@breadceo 왈, 빌드 속도 향상을 위해 적용했다고 합니다.) 다음 페이지들을 참고하여 해당 기법을 이용할 경우 module화가 가능하며 직방이 관리하는 next.js 빌드 버전을 이용하지 않을 수 있을 것으로 예상 됩니다.

- https://nextjs.org/docs#customizing-webpack-config
- https://github.com/zeit/next.js/tree/master/packages/next-bundle-analyzer

(@xeoh 님 내용 참고)

**Comment by breadceo** [comment]
zigbang-client 에 작업완료되었습니다. commit hash: 41f390e140e5fac63160be9557c9181cdff5609f
배포 후에 삭제 요청드리겠습니다 :)
